### PR TITLE
Hello World in Java by Zach

### PR DESCRIPTION
**Pull request by 02zchen**
### What the program do ?
It prints out Hello World
----

### In what programming language it is written?
java

### CODE REVIEW

**Comment by Aniket965** [comment]
This pull request do not contains files in specific folders. Please fix it and reopen

**Comment by 02zchen** [comment]
Ok, I will fix that. Sorry about that.

**Comment by 02zchen** [comment]
I'm sorry to bother you, but this is my first time doing this. How do you
reopen a pull request? I tried searching online but I got no definitive
answer. Most said that I can't reopen a pull request if I am not the owner.

Thanks,
Zach

**Comment by 02zchen** [comment]
Ok, thanks.

**Pull request closed without merging**
